# Generated by Django 5.0.6 on 2024-06-06 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('gen_male', 'M'), ('gen_female', 'F')], default='gen_male', max_length=10)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('qualification', models.CharField(default=False, max_length=100)),
                ('year_of_experience', models.IntegerField(default=0)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('email', models.EmailField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract')], default='FT', max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateField()),
                ('no_of_vacancy', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.CharField(max_length=255)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qualification', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=255)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('resume', models.FileField(upload_to='')),
                ('cover_letter', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applicant')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job')),
            ],
        ),
    ]
