# Generated by Django 5.0.6 on 2024-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_applicant_job_title_alter_applicant_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicanttracking',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
